// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module.Auth.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Module.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260915041321_AddBranchCompleteSince")]
    partial class AddBranchCompleteSince
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Module.Auth.Domain.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AllowedFeatureKeys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompleteSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Module.Auth.Domain.Feature", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMenu")
                        .HasColumnType("boolean");

                    b.Property<int>("Module")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Module.Auth.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AllowedFeatureKeys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("integer");

                    b.Property<int>("MaxExtraRoles")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Module.Auth.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Module.Auth.Domain.RoleFeaturePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey");

                    b.HasIndex("RoleId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("RoleFeaturePermissions");
                });

            modelBuilder.Entity("Module.Auth.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DataBaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlanId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Module.Auth.Domain.TenantDataBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TenantDatabases");
                });

            modelBuilder.Entity("Module.Auth.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalAuthId")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordChangeTicket")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordChangeTicketExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Module.Auth.Domain.UserBranchRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "BranchId", "RoleId");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserBranchRoles");
                });

            modelBuilder.Entity("Module.Auth.Domain.Branch", b =>
                {
                    b.HasOne("Module.Auth.Domain.Tenant", "Tenant")
                        .WithMany("Branches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Module.Auth.Domain.Feature", b =>
                {
                    b.OwnsMany("Module.Auth.Domain.FeatureAction", "AvailableActions", b1 =>
                        {
                            b1.Property<string>("FeatureKey")
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FeatureKey", "__synthesizedOrdinal");

                            b1.ToTable("Features");

                            b1.ToJson("AvailableActions");

                            b1.WithOwner()
                                .HasForeignKey("FeatureKey");
                        });

                    b.Navigation("AvailableActions");
                });

            modelBuilder.Entity("Module.Auth.Domain.Plan", b =>
                {
                    b.OwnsOne("Common.Contracts.inventory.DefaultCatalogTemplate", "DefaultCatalogTemplate", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("Colors")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("PlanId");

                            b1.ToTable("Plans");

                            b1.ToJson("DefaultCatalogTemplate");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");

                            b1.OwnsMany("Common.Contracts.inventory.DefaultBrandTemplate", "Brands", b2 =>
                                {
                                    b2.Property<Guid>("DefaultCatalogTemplatePlanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Prefix")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DefaultCatalogTemplatePlanId", "__synthesizedOrdinal");

                                    b2.ToTable("Plans");

                                    b2.WithOwner()
                                        .HasForeignKey("DefaultCatalogTemplatePlanId");
                                });

                            b1.OwnsMany("Common.Contracts.inventory.DefaultCategoryTemplate", "Categories", b2 =>
                                {
                                    b2.Property<Guid>("DefaultCatalogTemplatePlanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DefaultCatalogTemplatePlanId", "__synthesizedOrdinal");

                                    b2.ToTable("Plans");

                                    b2.WithOwner()
                                        .HasForeignKey("DefaultCatalogTemplatePlanId");
                                });

                            b1.OwnsMany("Common.Contracts.inventory.DefaultSizeTemplate", "Sizes", b2 =>
                                {
                                    b2.Property<Guid>("DefaultCatalogTemplatePlanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("SortOrder")
                                        .HasColumnType("integer");

                                    b2.HasKey("DefaultCatalogTemplatePlanId", "__synthesizedOrdinal");

                                    b2.ToTable("Plans");

                                    b2.WithOwner()
                                        .HasForeignKey("DefaultCatalogTemplatePlanId");
                                });

                            b1.Navigation("Brands");

                            b1.Navigation("Categories");

                            b1.Navigation("Sizes");
                        });

                    b.OwnsMany("Module.Auth.Domain.DefaultRoleTemplate", "DefaultRolesTemplate", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PlanId", "__synthesizedOrdinal");

                            b1.ToTable("Plans");

                            b1.ToJson("DefaultRolesTemplate");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");

                            b1.OwnsMany("Module.Auth.Domain.DefaultRolePermissionTemplate", "Permissions", b2 =>
                                {
                                    b2.Property<Guid>("DefaultRoleTemplatePlanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("DefaultRoleTemplate__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.PrimitiveCollection<List<string>>("Actions")
                                        .IsRequired()
                                        .HasColumnType("text[]");

                                    b2.Property<string>("FeatureKey")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DefaultRoleTemplatePlanId", "DefaultRoleTemplate__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Plans");

                                    b2.WithOwner()
                                        .HasForeignKey("DefaultRoleTemplatePlanId", "DefaultRoleTemplate__synthesizedOrdinal");
                                });

                            b1.Navigation("Permissions");
                        });

                    b.Navigation("DefaultCatalogTemplate");

                    b.Navigation("DefaultRolesTemplate");
                });

            modelBuilder.Entity("Module.Auth.Domain.RoleFeaturePermission", b =>
                {
                    b.HasOne("Module.Auth.Domain.Feature", "Feature")
                        .WithMany("RoleFeaturePermissions")
                        .HasForeignKey("FeatureKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Module.Auth.Domain.Role", "Role")
                        .WithMany("RoleFeaturePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Module.Auth.Domain.Tenant", b =>
                {
                    b.HasOne("Module.Auth.Domain.TenantDataBase", "TenantDataBase")
                        .WithMany("Tenants")
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Auth.Domain.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Module.Auth.Domain.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");

                    b.Navigation("Plan");

                    b.Navigation("TenantDataBase");
                });

            modelBuilder.Entity("Module.Auth.Domain.UserBranchRole", b =>
                {
                    b.HasOne("Module.Auth.Domain.Branch", "Branch")
                        .WithMany("UserBranchRoles")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Auth.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Auth.Domain.User", "User")
                        .WithMany("UserBranchRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Module.Auth.Domain.Branch", b =>
                {
                    b.Navigation("UserBranchRoles");
                });

            modelBuilder.Entity("Module.Auth.Domain.Feature", b =>
                {
                    b.Navigation("RoleFeaturePermissions");
                });

            modelBuilder.Entity("Module.Auth.Domain.Role", b =>
                {
                    b.Navigation("RoleFeaturePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Module.Auth.Domain.Tenant", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("Module.Auth.Domain.TenantDataBase", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Module.Auth.Domain.User", b =>
                {
                    b.Navigation("UserBranchRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
